# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitHooks < Formula
  desc ""
  homepage "https://github.com/rudderlabs/git-hooks/"
  version "1.1.2"

  depends_on "gitleaks" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudderlabs/git-hooks/releases/download/v1.1.2/git-hooks_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "7a322a2bebaffd32aec398e050edab1eb524c59a6aa7e8036fc5a0ea0619c385"

      def install
        bin.install "git-hooks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudderlabs/git-hooks/releases/download/v1.1.2/git-hooks_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "e8e19fe12b925ff65292427b681bcf5afc6101bd1942a7117120f063f703d221"

      def install
        bin.install "git-hooks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudderlabs/git-hooks/releases/download/v1.1.2/git-hooks_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "b57c1b9bcbd9620cd1081c896e2d3b5f6d779d7540a055b593d124319c7b7037"
      def install
        bin.install "git-hooks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudderlabs/git-hooks/releases/download/v1.1.2/git-hooks_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "0cf03a2a4f8b001af6ea6d125a2210a8605ede86346e8ae4e15b2a6b4f77246e"
      def install
        bin.install "git-hooks"
      end
    end
  end

  test do
    system "#{bin}/git-hooks"
  end
end
